# Generated by Django 5.0.1 on 2024-01-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_main'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('tagline', models.CharField(max_length=30)),
                ('content', models.CharField(max_length=100)),
                ('image', models.ImageField(default='static/main/images/5856.jpg', upload_to='images/')),
            ],
        ),
    ]
