# Generated by Django 5.0.1 on 2024-01-27 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='tagline',
            field=models.CharField(default='Hello', max_length=20),
        ),
    ]
