# Generated by Django 5.0.1 on 2024-01-27 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_objective'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(default='static/main/images/5856.jpg', upload_to='images/')),
                ('name', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
            ],
        ),
    ]
