# Generated by Django 5.0.1 on 2024-01-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_innovation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('image', models.ImageField(default='static/main/images/5856.jpg', upload_to='images/')),
                ('tagline', models.CharField(default='Hello', max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('url', models.URLField()),
            ],
        ),
    ]
