# Generated by Django 5.0.1 on 2024-01-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='about',
            name='tagline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='application',
            name='tagline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='innovation',
            name='tagline',
            field=models.CharField(default='Hello', max_length=100),
        ),
        migrations.AlterField(
            model_name='main',
            name='content',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='main',
            name='tagline',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mission',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='mission',
            name='tagline',
            field=models.CharField(default='Hello', max_length=100),
        ),
        migrations.AlterField(
            model_name='objective',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='objective',
            name='tagline',
            field=models.CharField(default='Hello', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='project',
            name='tagline',
            field=models.CharField(default='Hello', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='designation',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='vision',
            name='description',
            field=models.CharField(max_length=600),
        ),
    ]
